services:
  - type: worker
    name: telegram-video-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    environment:
      TELEGRAM_TOKEN: 7039618376:AAEEx3Yp2Mto2GChJ2M5w01ugyPQbJhePeA
      pythonVersion: 3.11.7
