services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 10000
      - key: TELEGRAM_TOKEN
        fromDatabase: false
        value: 7039618376:AAEEx3Yp2Mto2GChJ2M5w01ugyPQbJhePeA
